controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      node_options_args:
        - --ros-args
        - --params-file
        - /home/zhan/train_robot-main/train_robot/ros2_ws/src/robot_description/config/gazebo_controllers.yaml

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      node_options_args:
        - --ros-args
        - --params-file
        - /home/zhan/train_robot-main/train_robot/ros2_ws/src/robot_description/config/gazebo_controllers.yaml


velocity_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
      - wl1_joint
      - wl2_joint
      - wr1_joint
      - wr2_joint
